# Generated by Django 3.1.7 on 2021-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('privilege', models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist')], max_length=50)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('adress', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('salary', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
