# Generated by Django 3.1.7 on 2021-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('informations', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('refundable', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
