# Generated by Django 3.1.7 on 2021-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20210518_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='results',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
